const { v4: uuidv4 } = require("uuid");
const apiBasicInfo = [
  {
    id: uuidv4(),
    name: "Blush",
    api_product_type_value: "blush",
    img_src: "https://img.icons8.com/ios/100/000000/cosmetic-brush.png",
  },
  {
    id: uuidv4(),
    name: "Bronzer",
    api_product_type_value: "bronzer",
    img_src:
      "https://img.icons8.com/fluent-systems-regular/96/000000/eye-shadows.png",
  },
  {
    id: uuidv4(),
    name: "Eyebrow",
    api_product_type_value: "eyebrow",
    img_src: "https://img.icons8.com/ios/100/000000/eyebrow.png",
  },
  {
    id: uuidv4(),
    name: "Eyeliner",
    api_product_type_value: "eyeliner",
    img_src: "https://img.icons8.com/material-rounded/96/000000/pencil-tip.png",
  },
  {
    id: uuidv4(),
    name: "Eyeshadow",
    api_product_type_value: "eyeshadow",
    img_src: "https://img.icons8.com/ios/100/000000/eye-shadows--v2.png",
  },
  {
    id: uuidv4(),
    name: "Foundation",
    api_product_type_value: "foundation",
    img_src: "https://img.icons8.com/ios/100/000000/foundation-makeup.png",
  },
  {
    id: uuidv4(),
    name: "Lip liner",
    api_product_type_value: "lip_liner",
    img_src:
      "https://img.icons8.com/material-outlined/96/000000/pencil-tip.png",
  },
  {
    id: uuidv4(),
    name: "Lipstick",
    api_product_type_value: "lipstick",
    img_src: "https://img.icons8.com/ios/100/000000/lipstick.png",
  },
  {
    id: uuidv4(),
    name: "Mascara",
    api_product_type_value: "mascara",
    img_src: "https://img.icons8.com/dotty/50/000000/mascara.png",
  },
  {
    id: uuidv4(),
    name: "Nail Polish",
    api_product_type_value: "nail_polish",
    img_src: "https://img.icons8.com/ios/100/000000/nail-polish.png",
  },
];

const brands = [
  { id: uuidv4(), name: "Almay", api_brand_value: "almay" },
  { id: uuidv4(), name: "Alva", api_brand_value: "alva" },
  { id: uuidv4(), name: "Anna Sui", api_brand_value: "anna sui" },
  { id: uuidv4(), name: "Annabelle", api_brand_value: "annabelle" },
  { id: uuidv4(), name: "Benefit", api_brand_value: "benefit" },
  { id: uuidv4(), name: "Boosh", api_brand_value: "Boosh" },
  { id: uuidv4(), name: "Burt's Bees", api_brand_value: "burt's bees" },
  {
    id: uuidv4(),
    name: "Butter London",
    api_brand_value: "butter london",
  },
  { id: uuidv4(), name: "C'est Moi", api_brand_value: "c'est moi" },
  {
    id: uuidv4(),
    name: "Cargo Cosmetics",
    api_brand_value: "cargo cosmetics",
  },
  { id: uuidv4(), name: "China Glaze", api_brand_value: "china glaze" },
  { id: uuidv4(), name: "Clinique", api_brand_value: "clinique" },
  {
    id: uuidv4(),
    name: "Coastal Classic Creation",
    api_brand_value: "coastal classic creation",
  },
  { id: uuidv4(), name: "Colourpop", api_brand_value: "colourpop" },
  { id: uuidv4(), name: "Covergirl", api_brand_value: "covergirl" },
  { id: uuidv4(), name: "Dalish", api_brand_value: "dalish" },
  { id: uuidv4(), name: "Deciem", api_brand_value: "deciem" },
  { id: uuidv4(), name: "Dior", api_brand_value: "Dior" },
  {
    id: uuidv4(),
    name: "Dr. Hauschka",
    api_brand_value: "dr. hauschka",
  },
  { id: uuidv4(), name: "E.L.F.", api_brand_value: "e.l.f." },
  { id: uuidv4(), name: "Essie", api_brand_value: "essie" },
  { id: uuidv4(), name: "Fenty", api_brand_value: "fenty" },
  { id: uuidv4(), name: "Glossier", api_brand_value: "glossier" },
  {
    id: uuidv4(),
    name: "Green People",
    api_brand_value: "green people",
  },
  { id: uuidv4(), name: "Iman", api_brand_value: "iman" },
  { id: uuidv4(), name: "L'oreal", api_brand_value: "l'oreal" },
  {
    id: uuidv4(),
    name: "Lotus Cosmetics USA",
    api_brand_value: "lotus cosmetics usa",
  },
  {
    id: uuidv4(),
    name: "Maia's Mineral Galaxy",
    api_brand_value: "maia's mineral galaxy",
  },
  { id: uuidv4(), name: "Marcelle", api_brand_value: "marcelle" },
  { id: uuidv4(), name: "Marienatie", api_brand_value: "marienatie" },
  { id: uuidv4(), name: "Maybelline", api_brand_value: "maybelline" },
  { id: uuidv4(), name: "Milani", api_brand_value: "milani" },
  {
    id: uuidv4(),
    name: "Mineral Fusion",
    api_brand_value: "mineral fusion",
  },
  { id: uuidv4(), name: "Misa", api_brand_value: "misa" },
  { id: uuidv4(), name: "Mistura", api_brand_value: "mistura" },
  { id: uuidv4(), name: "Moov", api_brand_value: "moov" },
  { id: uuidv4(), name: "Nudus", api_brand_value: "nudus" },
  { id: uuidv4(), name: "NYX", api_brand_value: "nyx" },
  { id: uuidv4(), name: "Orly", api_brand_value: "orly" },
  { id: uuidv4(), name: "Pacifica", api_brand_value: "pacifica" },
  {
    id: uuidv4(),
    name: "Penny Lane Organics",
    api_brand_value: "penny lane organics",
  },
  {
    id: uuidv4(),
    name: "Physicians Formula",
    api_brand_value: "physicians formula",
  },
  { id: uuidv4(), name: "Piggy Paint", api_brand_value: "piggy paint" },
  { id: uuidv4(), name: "Pure Anada", api_brand_value: "pure anada" },
  { id: uuidv4(), name: "Rejuva Minerals", api_brand_value: "rejuva minerals" },
  { id: uuidv4(), name: "Revlon", api_brand_value: "revlon" },
  {
    id: uuidv4(),
    name: "Sally B's Skin Yummies",
    api_brand_value: "sally b's skin yummies",
  },
  { id: uuidv4(), name: "Salon Perfect", api_brand_value: "salon perfect" },
  { id: uuidv4(), name: "Sante", api_brand_value: "sante" },
  { id: uuidv4(), name: "Sinful Colours", api_brand_value: "sinful colours" },
  { id: uuidv4(), name: "Smashbox", api_brand_value: "smashbox" },
  { id: uuidv4(), name: "Stila", api_brand_value: "stila" },
  { id: uuidv4(), name: "Suncoat", api_brand_value: "suncoat" },
  { id: uuidv4(), name: "W3llpeople", api_brand_value: "w3llpeople" },
  { id: uuidv4(), name: "Wet N Wild", api_brand_value: "wet n wild" },
  { id: uuidv4(), name: "Zorah", api_brand_value: "zorah" },
  {
    id: uuidv4(),
    name: "Zorah Biocosmetiques",
    api_brand_value: "zorah biocosmetiques",
  },
];

module.exports = { apiBasicInfo, brands };
